#!/usr/bin/env bash
LOG=/var/log/sys_health.log
DATE=$(date +"%Y-%m-%d %H:%M:%S")
CPU=$(awk -v FS=" " '/^cpu /{usage=(($2+$4)*100)/($2+$4+$5)} END{printf "%.2f", usage}' /proc/stat)
MEM=$(free -m | awk '/Mem:/{printf "%s/%sMB(%.2f%%)", $3,$2, $3*100/$2}')
DISK=$(df -h / | awk 'NR==2{print $3 "/" $2 " (" $5 ")"}')
echo "$DATE CPU:${CPU}% MEM:${MEM} DISK:${DISK}" | sudo tee -a "$LOG" >/dev/null
